//! GENERATED by `node tools/gen-unit-names.mjs` - do not hand-edit.
//!
//! In-game unit display names and the player-unit roster, baked from the
//! re-MAX rules inis (`assets/config/rules/object_types`). The tags are the
//! same `ResourceID` names as [`UNIT_TYPE_NAMES`](super::UNIT_TYPE_NAMES);
//! both tables ride in canonical id order.

/// `ResourceID` tag -> the unit's proper in-game name (`Name=` in the rules
/// inis). Tags without a section or with an empty name (decoration, FX, the
/// unnamed SUPRTPLT) are absent - display falls back to the tag.
pub const UNIT_DISPLAY_NAMES: [(&str, &str); 70] = [
	("COMMTWR", "Gold Refinery"),
	("POWERSTN", "Power Station"),
	("POWGEN", "Power Generator"),
	("BARRACKS", "Barracks"),
	("SHIELDGN", "Monopole Mine"),
	("RADAR", "Radar"),
	("ADUMP", "Storage Unit"),
	("FDUMP", "Fuel Tank"),
	("GOLDSM", "Gold Vault"),
	("DEPOT", "Depot"),
	("HANGAR", "Hangar"),
	("DOCK", "Dock"),
	("CNCT_4W", "Connector"),
	("ROAD", "Road"),
	("LANDPAD", "Landing Pad"),
	("SHIPYARD", "Shipyard"),
	("LIGHTPLT", "Light Vehicle Plant"),
	("LANDPLT", "Heavy Vehicle Plant"),
	("AIRPLT", "Air Units Plant"),
	("HABITAT", "Habitat"),
	("RESEARCH", "Research Center"),
	("GREENHSE", "Eco-sphere"),
	("RECCENTR", "Recreation Center"),
	("TRAINHAL", "Training Hall"),
	("WTRPLTFM", "Water Platform"),
	("GUNTURRT", "Gun Turret"),
	("ANTIAIR", "Anti Aircraft"),
	("ARTYTRRT", "Artillery"),
	("ANTIMSSL", "Missile Launcher"),
	("BLOCK", "Concrete Block"),
	("BRIDGE", "Bridge"),
	("MININGST", "Mining Station"),
	("LANDMINE", "Land Mine"),
	("SEAMINE", "Sea Mine"),
	("MASTER", "Master Builder"),
	("CONSTRCT", "Constructor"),
	("SCOUT", "Scout"),
	("TANK", "Tank"),
	("ARTILLRY", "Assault Gun"),
	("ROCKTLCH", "Rocket Launcher"),
	("MISSLLCH", "Missile Crawler"),
	("SP_FLAK", "Mobile Anti Aircraft"),
	("MINELAYR", "Mine Layer"),
	("SURVEYOR", "Surveyor"),
	("SCANNER", "Scanner"),
	("SPLYTRCK", "Supply Truck"),
	("GOLDTRCK", "Gold Truck"),
	("ENGINEER", "Engineer"),
	("BULLDOZR", "Bulldozer"),
	("REPAIR", "Repair Unit"),
	("FUELTRCK", "Fuel Truck"),
	("CLNTRANS", "Personnel Carrier"),
	("COMMANDO", "Infiltrator"),
	("INFANTRY", "Infantry"),
	("FASTBOAT", "Escort"),
	("CORVETTE", "Corvette"),
	("BATTLSHP", "Gunboat"),
	("SUBMARNE", "Submarine"),
	("SEATRANS", "Sea Transport"),
	("MSSLBOAT", "Missile Cruiser"),
	("SEAMNLYR", "Sea Mine Layer"),
	("CARGOSHP", "Cargo Ship"),
	("FIGHTER", "Fighter"),
	("BOMBER", "Ground Attack Plane"),
	("AIRTRANS", "Air Transport"),
	("AWAC", "AWAC"),
	("JUGGRNT", "Alien Gunboat"),
	("ALNTANK", "Alien Tank"),
	("ALNASGUN", "Alien Assault Gun"),
	("ALNPLANE", "Alien Attack Plane"),
];

/// Tags of every unit players can build and control - the set the game's own
/// upgrade menus offer: neither `Buildable=no` (alien units, scenario-only
/// buildings) nor `Passive=yes` (road/bridge/platform/block dressing), minus
/// the factory-less MASTER. LANDMINE and SEAMINE ride along because the
/// engine lists a mine whenever its deployer is buildable
/// (`AbstractUpgradeMenu::IsUnitFiltered`).
pub const PLAYER_UNIT_TAGS: [&str; 60] = [
	"COMMTWR", "POWERSTN", "POWGEN", "BARRACKS", "RADAR", "ADUMP", "FDUMP", "GOLDSM", "DEPOT", "HANGAR", "DOCK",
	"CNCT_4W", "LANDPAD", "SHIPYARD", "LIGHTPLT", "LANDPLT", "SUPRTPLT", "AIRPLT", "HABITAT", "RESEARCH", "GREENHSE",
	"TRAINHAL", "GUNTURRT", "ANTIAIR", "ARTYTRRT", "ANTIMSSL", "MININGST", "LANDMINE", "SEAMINE", "CONSTRCT", "SCOUT",
	"TANK", "ARTILLRY", "ROCKTLCH", "MISSLLCH", "SP_FLAK", "MINELAYR", "SURVEYOR", "SCANNER", "SPLYTRCK", "GOLDTRCK",
	"ENGINEER", "BULLDOZR", "REPAIR", "FUELTRCK", "CLNTRANS", "COMMANDO", "INFANTRY", "FASTBOAT", "CORVETTE",
	"BATTLSHP", "SUBMARNE", "SEATRANS", "MSSLBOAT", "SEAMNLYR", "CARGOSHP", "FIGHTER", "BOMBER", "AIRTRANS", "AWAC",
];

/// The proper in-game name for a `ResourceID` tag, `None` where the rules
/// carry no (non-empty) name - callers show the tag itself then.
pub fn unit_display_name(tag: &str) -> Option<&'static str> {
	UNIT_DISPLAY_NAMES.iter().find(|(t, _)| *t == tag).map(|(_, n)| *n)
}

/// Whether a save `unit_type` is a unit players can build and control (see
/// [`PLAYER_UNIT_TAGS`]) - the Upgrades roster and its validation gate.
pub fn is_player_unit_type(unit_type: u16) -> bool {
	super::unit_type_name(unit_type).is_some_and(|tag| PLAYER_UNIT_TAGS.contains(&tag))
}
