//! Monospace bitmap atlas for the in-app console (copied from world-editor;
//! originally @generated by its tools/gen_console_font.py from
//! Hack-Regular.ttf). Printable ASCII 0x20..=0x7e packed left-to-right in one
//! row, 8-bit coverage.

/// Glyph cell size, pixels.
pub const CELL_W: u32 = 10;
pub const CELL_H: u32 = 19;
/// First atlas character (space); a glyph's column index is `code - FIRST`.
pub const FIRST: u8 = 32;
pub const COUNT: u32 = 95;
/// Atlas size (one row of `COUNT` cells), single-channel R8 coverage.
pub const ATLAS_W: u32 = 950;
pub const ATLAS_H: u32 = 19;
pub static ATLAS: &[u8] = include_bytes!("../assets/console_font.bin");
