//! @generated by world-editor tools/gen_max_font.py from
//! MAX_Redesign_Square.ttf -- DO NOT EDIT (copied verbatim).
//! Proportional bitmap atlas for UI **labels**: printable ASCII
//! 0x20..=0x7e packed left-to-right, 8-bit coverage, with per-glyph
//! advance/offset tables for layout (see `text::push_label`).

/// Atlas height = font cell height (ascent + descent), pixels.
pub const CELL_H: u32 = 60;
/// First atlas character (space); a glyph's index is `code - FIRST`.
pub const FIRST: u8 = 32;
pub const COUNT: u32 = 95;
/// Atlas width (sum of glyph advances), single-channel R8 coverage.
pub const ATLAS_W: u32 = 3332;

/// Per-glyph advance width (= its cell width), pixels.
pub static ADVANCE: [u16; 95] = [
	48, 12, 28, 40, 36, 64, 48, 16, 20, 20, 32, 36, 16, 24, 12, 32, 36, 20, 36, 36, 40, 36, 36, 36, 36, 36, 12, 16, 40,
	28, 40, 36, 52, 52, 40, 40, 40, 40, 40, 40, 44, 20, 36, 44, 40, 52, 44, 40, 40, 40, 40, 40, 44, 40, 48, 60, 40, 36,
	36, 20, 32, 20, 40, 40, 28, 36, 36, 32, 32, 32, 36, 32, 36, 16, 28, 36, 20, 52, 40, 32, 36, 36, 32, 32, 32, 40, 40,
	56, 44, 36, 40, 28, 12, 28, 32,
];
/// Per-glyph x offset (start column) in the atlas.
pub static OFFSET: [u16; 95] = [
	0, 48, 60, 88, 128, 164, 228, 276, 292, 312, 332, 364, 400, 416, 440, 452, 484, 520, 540, 576, 612, 652, 688, 724,
	760, 796, 832, 844, 860, 900, 928, 968, 1004, 1056, 1108, 1148, 1188, 1228, 1268, 1308, 1348, 1392, 1412, 1448,
	1492, 1532, 1584, 1628, 1668, 1708, 1748, 1788, 1828, 1872, 1912, 1960, 2020, 2060, 2096, 2132, 2152, 2184, 2204,
	2244, 2284, 2312, 2348, 2384, 2416, 2448, 2480, 2516, 2548, 2584, 2600, 2628, 2664, 2684, 2736, 2776, 2808, 2844,
	2880, 2912, 2944, 2976, 3016, 3056, 3112, 3156, 3192, 3232, 3260, 3272, 3300,
];

pub static ATLAS: &[u8] = include_bytes!("../assets/max_font.bin");
